// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTq_3GR5CHzfwZWxdIwDkw0MFRWTHv-4Y',
    appId: '1:973190005434:web:ff491db12b659cf429f883',
    messagingSenderId: '973190005434',
    projectId: 'wasfa-rider',
    authDomain: 'wasfa-rider.firebaseapp.com',
    storageBucket: 'wasfa-rider.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFpyAvqbEowx_ay7DZAFpXxeTJdxWBtE',
    appId: '1:973190005434:android:09a6db563214c3a729f883',
    messagingSenderId: '973190005434',
    projectId: 'wasfa-rider',
    storageBucket: 'wasfa-rider.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdKPdX0Fp5cw2cD0qIJk2z8dMdh0o1PI',
    appId: '1:973190005434:ios:bbd6e3e8c22767a029f883',
    messagingSenderId: '973190005434',
    projectId: 'wasfa-rider',
    storageBucket: 'wasfa-rider.firebasestorage.app',
    iosBundleId: 'kw.wasfa.rider',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdKPdX0Fp5cw2cD0qIJk2z8dMdh0o1PI',
    appId: '1:973190005434:ios:bbd6e3e8c22767a029f883',
    messagingSenderId: '973190005434',
    projectId: 'wasfa-rider',
    storageBucket: 'wasfa-rider.firebasestorage.app',
    iosBundleId: 'kw.wasfa.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTq_3GR5CHzfwZWxdIwDkw0MFRWTHv-4Y',
    appId: '1:973190005434:web:41b35df7ed12dc5529f883',
    messagingSenderId: '973190005434',
    projectId: 'wasfa-rider',
    authDomain: 'wasfa-rider.firebaseapp.com',
    storageBucket: 'wasfa-rider.firebasestorage.app',
  );
}