/// Lightweight i18n matching the HTML prototype's I18N dictionary.
import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../../presentation/viewmodels/app_viewmodel.dart';

class AppStrings {
  const AppStrings(this.locale);
  final String locale;

  static const Map<String, Map<String, String>> _dict = {
    'en': {
      'appName':       'WASFA Rider',
      'onShift':       'ON SHIFT',
      'offShift':      'OFF SHIFT',
      'today':         'TODAY',
      'welcome':       'Welcome',
      'enterPhone':    'Enter your phone number',
      'sendCode':      'Send code',
      'enterCode':     'Enter verification code',
      'sentTo':        'We sent a 6-digit code to',
      'resend':        'Resend code',
      'verify':        'Verify',
      'setupVehicle':  'Set up your vehicle',
      'vehicleType':   'Vehicle type',
      'plate':         'Plate number',
      'continue_':     'Continue',
      'motorbike':     'Motorbike',
      'scooter':       'Scooter',
      'car':           'Car',
      'pickLang':      'Choose your language',
      'english':       'English',
      'arabic':        'العربية',
      'logout':        'Logout',
      'orders':        'Orders',
      'home':          'Home',
      'profile':       'Profile',
      'history':       'History',
      'earnings':      'Earnings',
      'active':        'Active',
      'done':          'Done',
      'all':           'All',
      'swipeArrived':  'Swipe when arrived',
      'headingToPharmacy': "I'm on my way to pharmacy",
      'confirmPickedUp': 'Confirm items picked up',
      'headingToPatient': 'Heading to patient (open directions)',
      'arrivedAtPatient': "I've arrived at patient",
      'cantDeliver':   "Can't deliver — failed",
      'openInMaps':    'OPEN IN MAPS',
      'call':          'Call',
      'maps':          'Maps',
      'waze':          'Waze',
      'allDone':       'All done!',
      'noMoreStops':   'No more active stops. Waiting for new orders…',
      'tapPinHint':    'Tap any pin to make it stop #1',
      'emergencyDispatched': '🆘 Emergency dispatched',
      'km':            'KM',
      'roleZone':      '📍 ZONE',
      'roleBatch':     '🛵 BATCH',
      'roleExpress':   '🏍 EXPRESS',
      'kd':            'KD',
      'noOrdersYet':   'No orders here yet',
      'yesterday':     'Yesterday',
      'thisWeek':      'This Week',
      'needsCollection': 'NEEDS COLLECTION',
      'link':          'LINK',
      'map':           'MAP',
      'callCap':       'CALL',
      'areaBlock':     'AREA · BLOCK',
      'streetHouse':   'STREET · HOUSE / APT',
      'landmark':      'LANDMARK',
      'todayFilter':   'Today',
      'driverPending':    'Pending',
      'driverCollecting': 'Collecting',
      'driverPickedUp':   'Picked up',
      'driverOnMyWay':    'On my way',
      'driverDelivered':  'Delivered',
      'driverFailed':     'Failed',
      'orderNotFound': 'Order not found',
      'whatsapp':      '💬 WhatsApp',
      'total':         'TOTAL',
      'paidCap':       'PAID',
      'useCardTerminal': 'Use card terminal at door',
      'knetCard':      'KNET CARD',
      'confirmPatientPaid': 'Confirm patient paid before handover',
      'linkCap':       'LINK',
      'exactChangePreferred': 'Exact change preferred',
      'cashOnDelivery': 'CASH ON DELIVERY',
      'paymentStatus': 'PAYMENT STATUS',
      'buildingPhoto': 'Building photo',
      'you':           'You',
      'cancel':        'CANCEL',
      'step1Heading':  'Step 1 of 4 · Heading to pharmacy',
      'step2Collecting': 'Step 2 of 4 · Collecting from pharmacy',
      'openPickupChecklist': 'Open pickup checklist',
      'confirmItemsPickedUp': 'Confirm items picked up',
      'step4OnTheWay': 'Step 4 of 4 · On the way · Swipe at the door',
      'alreadyPaidLabel': '✓ ALREADY PAID',
      'noCollectionNeeded': 'No collection needed — just deliver',
      'collectByKnet': '💳 COLLECT BY KNET',
      'paymentLinkSent': '🔗 PAYMENT LINK SENT',
      'collectCash':   '💵 COLLECT CASH',
      'totalToCollect': '💰 TOTAL TO COLLECT',
      'subtotal':      'Sub-total',
      'discount':      '🎁 Discount',
      'discountCap':   '🎁 DISCOUNT',
      'noDiscount':    '— no discount',
      'deliveryFee':   '🛵 Delivery',
      'buildingPhotosHeader': '🏢 BUILDING PHOTOS',
      'onFile':        'ON FILE',
      'byPrefix':      'by',
      'noPhotosYet':   'No photos yet — be the first to help future drivers find this building.',
      'addQuickNoteHint': "Add a quick note (e.g. 'beige building, blue door')",
      'saveAndShare':  '✓ SAVE & SHARE WITH DRIVERS',
      'deliveryFailedMsg': '🚫 Delivery failed',
      'deliveredComplete': '✓ Delivered — order complete',
      'headingToFirstPharmacy': "I'm on my way to first pharmacy",
      'step3ItemsInHand': 'Step 3 of 4 · Items in hand — head to patient',
      'collectPayment': 'Collect payment',
      'amountDue':     'AMOUNT DUE',
      'notPaidYet':    '⏳ NOT PAID YET',
      'cashLabel':     'Cash',
      'collectCashNow': 'Collect physical cash now',
      'knetLabel':     'KNET',
      'cardAtDoor':    'Card at the door',
      'sendPaymentLink': 'Send payment link',
      'whatsappCheckout': 'WhatsApp checkout to patient',
      'cashReceived':  'Cash received',
      'typeAmountGiven': 'Type the amount the patient gave',
      'orderTotalCap': 'ORDER TOTAL',
      'patientGave':   'PATIENT GAVE',
      'changeToGive':  'Change to give',
      'confirmCashReceived': 'Confirm cash received',
      'viaWhatsapp':   'via WhatsApp',
      'sendViaWhatsapp': 'Send via WhatsApp',
      'confirmHandover': 'Confirm handover',
      'confirmDelivery': 'Confirm delivery',
      'captureSignatureAbove': 'Capture signature above',
      'signWithFinger': 'SIGN WITH YOUR FINGER ABOVE THE LINE',
      'clear':         'Clear',
      'demoCode':      'Demo code: ',
      'deliveredBang': 'Delivered!',
      'earningsBump':  'Earnings bump',
      'startNextStop': 'Start next stop',
      'finishShift':   'Finish shift',
      'nextStopCap':   'NEXT STOP',
      'allDeliveriesDone': 'All deliveries done! Time for cash handover.',
      'patientNotHome': 'Patient not home',
      'patientRefused': 'Patient refused delivery',
      'wrongAddress':  'Wrong address',
      'patientNotReachable': 'Patient not reachable',
      'paymentIssue':  'Payment issue',
      'itemsDamaged':  'Items damaged',
      'otherReason':   'Other',
      'failedDeliveryTitle': 'Failed Delivery',
      'selectReason':  'Select a reason:',
      'additionalNotes': 'Additional notes (optional)',
      'reportAsFailed': 'Report as Failed',
      'viaLinkSuffix': 'via link',
      'patientPaysAutoMark': 'Patient pays from their phone. Order auto-marks PAID when payment lands.',
      'previewLabel':  '📎 Preview:',
      'whatsappPreviewTemplate': 'Hi {name}, your payment link for WASFA order #{id}: {link} · {total} KD',
      'recipientPrefix': 'Recipient',
      'podStep2':      'POD step 2 of 2 · #{id}',
      'signatureTab':  '✍️ Signature',
      'otpCodeTab':    '📱 OTP code',
      'typeSixDigitCode': 'Type the 6-digit code',
      'patientPrefix': 'Patient',
      'otpSentTemplate': 'A 6-digit code was just sent to {phone} via WhatsApp.\nAsk the patient and type it here.',
      'stopLabel':     'Stop',
      'orderPrefix':   'Order',
      'minLabel':      'min',
      'paidCheckmark': '✓ Paid',
      'batchPickupTitle': 'Batch Pickup',
      'ordersCollectedTemplate': '{picked} / {total} orders collected',
      'pickBtn':       'Pick',
      'startDeliveries': 'Start deliveries 🚀',
      'collectAllFirst': 'Collect all orders first',
      'itemsCountKdTemplate': '{items} items · {total} KD',
      'multiPharmacyPickupTitle': 'Multi-Pharmacy Pickup',
      'collectAllPharmaciesIntro': 'Collect from all {n} pharmacies before heading to the patient.',
      'itemsCountTemplate': '{n} items',
      'allPickedHeadToPatient': 'All picked — Head to patient 🛵',
      'collectFromAllFirst': 'Collect from all pharmacies first',
      'itemsToCollect': 'ITEMS TO COLLECT',
      'confirmPickupTemplate': 'Confirm pickup from {name}',
      'myDriverProfile': 'My driver profile',
      'personalInfoDocsEtc': 'Personal info · documents · vehicle · bank',
      'deliveryMode':  'DELIVERY MODE',
      'orderHistory':  'Order history',
      'allCompletedDeliveries': 'All completed deliveries',
      'languageCap':   'LANGUAGE',
      'logOut':        '🚪 Log out',
      'footerAppInfo': 'WASFA Rider V2',
      'footerConnected': 'Connected to the WASFA driver API.',
      'noCompletedOrdersYet': 'No completed orders yet',
      'deliveriesShowHere': 'Deliveries will show up here.',
      'completedDeliveriesTemplate': '{n} completed deliveries',
      'deliveredOnTemplate': 'Delivered {date}',
      'todayLower':    'today',
      'cashBadge':     'CASH',
      'personalInfo': 'Personal information',
      'fullNameEn': 'Full name (English)',
      'fullNameAr': 'Full name (Arabic)',
      'dobLabel': 'Date of birth',
      'nationalityLabel': 'Nationality',
      'civilIdLabel': 'Civil ID number (12 digits)',
      'civilIdExpiryLabel': 'Civil ID expiry',
      'bloodGroupLabel': 'Blood group',
      'contactSection': 'Contact',
      'primaryPhone': 'Primary phone',
      'whatsappNumber': 'WhatsApp number',
      'emailLabel': 'Email',
      'areaLabel': 'Area',
      'blockLabel': 'Block',
      'streetLabel': 'Street',
      'houseBuildingLabel': 'House / building',
      'emergencyContactSection': 'Emergency contact',
      'contactNameLabel': 'Contact name',
      'contactPhoneLabel': 'Contact phone',
      'relationshipLabel': 'Relationship',
      'employmentSection': 'Employment',
      'companyEmployerLabel': 'Company / employer',
      'employeeIdLabel': 'Employee ID',
      'joiningDateLabel': 'Joining date',
      'drivingExperienceLabel': 'Years of driving experience',
      'vehicleSection': 'Vehicle',
      'vehicleTypeLabel': 'Vehicle type',
      'plateNumberLabel': 'Plate number',
      'makeLabel': 'Make (Honda, Toyota…)',
      'modelLabel': 'Model',
      'yearLabel': 'Year',
      'colorLabel': 'Color',
      'bankAccountSection': 'Bank account (for commission payouts)',
      'bankLabel': 'Bank',
      'ibanLabel': 'IBAN',
      'beneficiaryNameLabel': 'Beneficiary name (as on bank)',
      'documentsSection': 'Documents — uploads required',
      'languagesSpokenHeader': 'LANGUAGES SPOKEN',
      'uploadedToast':  '✅ Uploaded',
      'percentComplete': '{n}% complete',
      'addYourName':    'Add your name',
      'profileCompletionTemplate': 'Profile completion · {n}% — finish all sections to keep working without interruptions',
      'uploadedStatus': 'Uploaded',
      'tapClearPhoto':  'Tap to take a clear photo',
      'retakeBtn':      'RETAKE',
      'uploadBtn':      'UPLOAD',
      'docCivilIdFront': 'Civil ID — FRONT',
      'docCivilIdBack': 'Civil ID — BACK',
      'docLicenseFront': 'Driving license — FRONT',
      'docLicenseBack': 'Driving license — BACK',
      'docVehicleReg':  'Vehicle registration / license',
      'docVehicleInsurance': 'Vehicle insurance',
      'photoOfMedication': '📸 Photo of medication at door',
      'podStep1':      'POD step 1 of 2 · Order #{id}',
      'myEarningsTab': '💰 My Earnings',
      'companyCashTab': '🏦 Company Cash',
      'myCommissionToday': 'MY COMMISSION TODAY',
      'deliveriesCountTemplate': '↑ {n} deliveries',
      'commissionRateLine1': 'Your commission rate (set by admin):\n',
      'commissionRatePercent': '10% of each order total',
      'weekLabel':     'Week',
      'monthLabel':    'Month',
      'hourlyCap':     'HOURLY',
      'deliveriesStatLabel': 'Deliveries',
      'failedStatLabel': 'Failed',
      'distanceStatLabel': 'Distance',
      'ratingStatLabel': 'Rating',
      'workAndHours':  'WORK & HOURS',
      'shiftTimeToday': 'SHIFT TIME TODAY',
      'liveStatus':    '● LIVE',
      'pausedStatus':  '◯ PAUSED',
      'idleStatLabel': 'Idle',
      'kdPerHourLabel': 'KD / hour',
      'shiftStarted':  'Shift started',
      'cashToHandOver': 'CASH TO HAND OVER',
      'cashHandoverExplainer': '💡 This is the cash you collected from CASH-paid orders.\nHand it over to your manager — they scan the QR — and it clears.',
      'cashHandoverQrToast': '📷 Cash handover QR — show to manager to confirm',
      'showQrToManager': '📷 Show QR to manager & hand over',
      'bankWithdrawToast': '🏦 Bank withdraw — attach receipt to continue',
      'withdrawToBank': '🏦 Withdraw to bank — attach receipt',
      'allClearNoCash': '✓ All clear — no cash to hand over',
      'recentHandovers': 'RECENT HANDOVERS',
      'noHandoversYet': 'No handovers yet. Once you hand over cash, history appears here.',
      'totalHandedOver': 'Total handed over',
      'bankBadge':     'BANK',
      'pendingBadge':  '⏳ PENDING',
      'confirmedBadge': '✓ CONFIRMED',
    },
    'ar': {
      'appName':       'سائق وصفة',
      'onShift':       'في الخدمة',
      'offShift':      'خارج الخدمة',
      'today':         'اليوم',
      'welcome':       'أهلاً بك',
      'enterPhone':    'أدخل رقم هاتفك',
      'sendCode':      'إرسال الرمز',
      'enterCode':     'أدخل رمز التحقق',
      'sentTo':        'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'resend':        'إعادة الإرسال',
      'verify':        'تحقق',
      'setupVehicle':  'إعداد المركبة',
      'vehicleType':   'نوع المركبة',
      'plate':         'رقم اللوحة',
      'continue_':     'متابعة',
      'motorbike':     'دراجة نارية',
      'scooter':       'سكوتر',
      'car':           'سيارة',
      'pickLang':      'اختر لغتك',
      'english':       'English',
      'arabic':        'العربية',
      'logout':        'تسجيل الخروج',
      'orders':        'الطلبات',
      'home':          'الرئيسية',
      'profile':       'الملف الشخصي',
      'history':       'السجل',
      'earnings':      'الأرباح',
      'active':        'نشط',
      'done':          'مكتمل',
      'all':           'الكل',
      'swipeArrived':  'اسحب عند الوصول',
      'headingToPharmacy': 'في طريقي إلى الصيدلية',
      'confirmPickedUp': 'تأكيد استلام الأصناف',
      'headingToPatient': 'في طريقي إلى المريض',
      'arrivedAtPatient': 'وصلت إلى المريض',
      'cantDeliver':   'تعذر التسليم',
      'openInMaps':    'فتح في الخريطة',
      'call':          'اتصال',
      'maps':          'خرائط',
      'waze':          'ويز',
      'allDone':       'انتهى الكل!',
      'noMoreStops':   'لا توجد محطات نشطة. في انتظار طلبات جديدة…',
      'tapPinHint':    'اضغط على أي دبوس لجعله المحطة الأولى',
      'emergencyDispatched': '🆘 تم إرسال طلب الطوارئ',
      'km':            'كم',
      'roleZone':      '📍 منطقة',
      'roleBatch':     '🛵 دفعة',
      'roleExpress':   '🏍 سريع',
      'kd':            'د.ك',
      'noOrdersYet':   'لا توجد طلبات هنا حتى الآن',
      'yesterday':     'أمس',
      'thisWeek':      'هذا الأسبوع',
      'needsCollection': 'يحتاج تحصيل',
      'link':          'رابط',
      'map':           'خريطة',
      'callCap':       'اتصال',
      'areaBlock':     'المنطقة · القطعة',
      'streetHouse':   'الشارع · المنزل / الشقة',
      'landmark':      'علامة بارزة',
      'todayFilter':   'اليوم',
      'driverPending':    'قيد الانتظار',
      'driverCollecting': 'جاري التحصيل',
      'driverPickedUp':   'تم الاستلام',
      'driverOnMyWay':    'في الطريق',
      'driverDelivered':  'تم التوصيل',
      'driverFailed':     'فشل',
      'orderNotFound': 'الطلب غير موجود',
      'whatsapp':      '💬 واتساب',
      'total':         'الإجمالي',
      'paidCap':       'مدفوع',
      'useCardTerminal': 'استخدم جهاز الدفع عند الباب',
      'knetCard':      'بطاقة كي نت',
      'confirmPatientPaid': 'تأكد من دفع المريض قبل التسليم',
      'linkCap':       'رابط',
      'exactChangePreferred': 'يفضل المبلغ الصحيح',
      'cashOnDelivery': 'الدفع عند الاستلام',
      'paymentStatus': 'حالة الدفع',
      'buildingPhoto': 'صورة المبنى',
      'you':           'أنت',
      'cancel':        'إلغاء',
      'step1Heading':  'الخطوة 1 من 4 · في الطريق إلى الصيدلية',
      'step2Collecting': 'الخطوة 2 من 4 · التحصيل من الصيدلية',
      'openPickupChecklist': 'فتح قائمة الاستلام',
      'confirmItemsPickedUp': 'تأكيد استلام الأصناف',
      'step4OnTheWay': 'الخطوة 4 من 4 · في الطريق · اسحب عند الباب',
      'alreadyPaidLabel': '✓ مدفوع مسبقاً',
      'noCollectionNeeded': 'لا حاجة للتحصيل — فقط قم بالتوصيل',
      'collectByKnet': '💳 تحصيل عبر كي نت',
      'paymentLinkSent': '🔗 تم إرسال رابط الدفع',
      'collectCash':   '💵 تحصيل نقدي',
      'totalToCollect': '💰 الإجمالي المطلوب تحصيله',
      'subtotal':      'المجموع الفرعي',
      'discount':      '🎁 الخصم',
      'discountCap':   '🎁 الخصم',
      'noDiscount':    '— لا يوجد خصم',
      'deliveryFee':   '🛵 التوصيل',
      'buildingPhotosHeader': '🏢 صور المبنى',
      'onFile':        'مسجلة',
      'byPrefix':      'بواسطة',
      'noPhotosYet':   'لا توجد صور حتى الآن — كن أول من يساعد السائقين القادمين في العثور على هذا المبنى.',
      'addQuickNoteHint': "أضف ملاحظة سريعة (مثال: 'مبنى بيج، باب أزرق')",
      'saveAndShare':  '✓ حفظ ومشاركة مع السائقين',
      'deliveryFailedMsg': '🚫 فشل التوصيل',
      'deliveredComplete': '✓ تم التوصيل — الطلب مكتمل',
      'headingToFirstPharmacy': 'في طريقي إلى أول صيدلية',
      'step3ItemsInHand': 'الخطوة 3 من 4 · الأصناف بحوزتك — توجه إلى المريض',
      'collectPayment': 'تحصيل الدفع',
      'amountDue':     'المبلغ المستحق',
      'notPaidYet':    '⏳ لم يتم الدفع بعد',
      'cashLabel':     'نقداً',
      'collectCashNow': 'تحصيل النقد الفعلي الآن',
      'knetLabel':     'كي نت',
      'cardAtDoor':    'الدفع بالبطاقة عند الباب',
      'sendPaymentLink': 'إرسال رابط الدفع',
      'whatsappCheckout': 'دفع عبر واتساب للمريض',
      'cashReceived':  'تم استلام النقد',
      'typeAmountGiven': 'أدخل المبلغ الذي أعطاه المريض',
      'orderTotalCap': 'إجمالي الطلب',
      'patientGave':   'المبلغ المستلم',
      'changeToGive':  'المبلغ المتبقي للمريض',
      'confirmCashReceived': 'تأكيد استلام النقد',
      'viaWhatsapp':   'عبر واتساب',
      'sendViaWhatsapp': 'إرسال عبر واتساب',
      'confirmHandover': 'تأكيد التسليم',
      'confirmDelivery': 'تأكيد التوصيل',
      'captureSignatureAbove': 'أخذ التوقيع أعلاه',
      'signWithFinger': 'وقّع بإصبعك أعلى الخط',
      'clear':         'مسح',
      'demoCode':      'رمز تجريبي: ',
      'deliveredBang': 'تم التوصيل!',
      'earningsBump':  'إضافة إلى الأرباح',
      'startNextStop': 'بدء المحطة التالية',
      'finishShift':   'إنهاء الدوام',
      'nextStopCap':   'المحطة التالية',
      'allDeliveriesDone': 'انتهت جميع التوصيلات! حان وقت تسليم النقد.',
      'patientNotHome': 'المريض غير موجود',
      'patientRefused': 'رفض المريض التوصيل',
      'wrongAddress':  'عنوان خاطئ',
      'patientNotReachable': 'تعذر الوصول إلى المريض',
      'paymentIssue':  'مشكلة في الدفع',
      'itemsDamaged':  'الأصناف تالفة',
      'otherReason':   'أخرى',
      'failedDeliveryTitle': 'فشل التوصيل',
      'selectReason':  'اختر السبب:',
      'additionalNotes': 'ملاحظات إضافية (اختياري)',
      'reportAsFailed': 'الإبلاغ كفاشل',
      'viaLinkSuffix': 'عبر الرابط',
      'patientPaysAutoMark': 'يدفع المريض من هاتفه. يتم تعليم الطلب كمدفوع تلقائياً عند استلام الدفع.',
      'previewLabel':  '📎 معاينة:',
      'whatsappPreviewTemplate': 'مرحباً {name}، رابط الدفع الخاص بطلب وصفة #{id}: {link} · {total} د.ك',
      'recipientPrefix': 'المستلم',
      'podStep2':      'إثبات التسليم خطوة 2 من 2 · #{id}',
      'signatureTab':  '✍️ التوقيع',
      'otpCodeTab':    '📱 رمز التحقق',
      'typeSixDigitCode': 'أدخل الرمز المكون من 6 أرقام',
      'patientPrefix': 'المريض',
      'otpSentTemplate': 'تم إرسال رمز مكون من 6 أرقام إلى {phone} عبر واتساب.\nاسأل المريض واكتبه هنا.',
      'stopLabel':     'المحطة',
      'orderPrefix':   'الطلب',
      'minLabel':      'د',
      'paidCheckmark': '✓ مدفوع',
      'batchPickupTitle': 'تحصيل الدفعة',
      'ordersCollectedTemplate': '{picked} / {total} طلبات محصلة',
      'pickBtn':       'تحصيل',
      'startDeliveries': 'بدء التوصيل 🚀',
      'collectAllFirst': 'حصّل جميع الطلبات أولاً',
      'itemsCountKdTemplate': '{items} أصناف · {total} د.ك',
      'multiPharmacyPickupTitle': 'تحصيل من عدة صيدليات',
      'collectAllPharmaciesIntro': 'حصّل من جميع {n} صيدليات قبل التوجه إلى المريض.',
      'itemsCountTemplate': '{n} أصناف',
      'allPickedHeadToPatient': 'تم تحصيل الكل — توجه إلى المريض 🛵',
      'collectFromAllFirst': 'حصّل من جميع الصيدليات أولاً',
      'itemsToCollect': 'الأصناف المطلوب تحصيلها',
      'confirmPickupTemplate': 'تأكيد التحصيل من {name}',
      'myDriverProfile': 'ملفي الشخصي',
      'personalInfoDocsEtc': 'المعلومات الشخصية · المستندات · المركبة · البنك',
      'deliveryMode':  'نمط التوصيل',
      'orderHistory':  'سجل الطلبات',
      'allCompletedDeliveries': 'جميع التوصيلات المكتملة',
      'languageCap':   'اللغة',
      'logOut':        '🚪 تسجيل الخروج',
      'footerAppInfo': 'وصفة رايدر V2',
      'footerConnected': 'متصل بواجهة برمجة تطبيقات السائق.',
      'noCompletedOrdersYet': 'لا توجد طلبات مكتملة حتى الآن',
      'deliveriesShowHere': 'ستظهر التوصيلات هنا.',
      'completedDeliveriesTemplate': '{n} توصيلات مكتملة',
      'deliveredOnTemplate': 'تم التوصيل {date}',
      'todayLower':    'اليوم',
      'cashBadge':     'نقداً',
      'personalInfo': 'المعلومات الشخصية',
      'fullNameEn': 'الاسم الكامل (إنجليزي)',
      'fullNameAr': 'الاسم الكامل (عربي)',
      'dobLabel': 'تاريخ الميلاد',
      'nationalityLabel': 'الجنسية',
      'civilIdLabel': 'الرقم المدني (12 رقم)',
      'civilIdExpiryLabel': 'تاريخ انتهاء البطاقة المدنية',
      'bloodGroupLabel': 'فئة الدم',
      'contactSection': 'التواصل',
      'primaryPhone': 'الهاتف الأساسي',
      'whatsappNumber': 'رقم واتساب',
      'emailLabel': 'البريد الإلكتروني',
      'areaLabel': 'المنطقة',
      'blockLabel': 'القطعة',
      'streetLabel': 'الشارع',
      'houseBuildingLabel': 'المنزل / المبنى',
      'emergencyContactSection': 'جهة اتصال الطوارئ',
      'contactNameLabel': 'اسم جهة الاتصال',
      'contactPhoneLabel': 'هاتف جهة الاتصال',
      'relationshipLabel': 'صلة القرابة',
      'employmentSection': 'التوظيف',
      'companyEmployerLabel': 'الشركة / صاحب العمل',
      'employeeIdLabel': 'رقم الموظف',
      'joiningDateLabel': 'تاريخ الانضمام',
      'drivingExperienceLabel': 'سنوات الخبرة في القيادة',
      'vehicleSection': 'المركبة',
      'vehicleTypeLabel': 'نوع المركبة',
      'plateNumberLabel': 'رقم اللوحة',
      'makeLabel': 'الصانع (هوندا، تويوتا…)',
      'modelLabel': 'الموديل',
      'yearLabel': 'السنة',
      'colorLabel': 'اللون',
      'bankAccountSection': 'الحساب البنكي (لصرف العمولات)',
      'bankLabel': 'البنك',
      'ibanLabel': 'الآيبان',
      'beneficiaryNameLabel': 'اسم المستفيد (كما في البنك)',
      'documentsSection': 'المستندات — التحميل مطلوب',
      'languagesSpokenHeader': 'اللغات المتحدثة',
      'uploadedToast':  '✅ تم التحميل',
      'percentComplete': '{n}% مكتمل',
      'addYourName':    'أضف اسمك',
      'profileCompletionTemplate': 'اكتمال الملف الشخصي · {n}% — أكمل جميع الأقسام لتجنب انقطاع العمل',
      'uploadedStatus': 'تم التحميل',
      'tapClearPhoto':  'اضغط لأخذ صورة واضحة',
      'retakeBtn':      'إعادة التصوير',
      'uploadBtn':      'تحميل',
      'docCivilIdFront': 'البطاقة المدنية — الأمام',
      'docCivilIdBack': 'البطاقة المدنية — الخلف',
      'docLicenseFront': 'رخصة القيادة — الأمام',
      'docLicenseBack': 'رخصة القيادة — الخلف',
      'docVehicleReg':  'استمارة / ترخيص المركبة',
      'docVehicleInsurance': 'تأمين المركبة',
      'photoOfMedication': '📸 صورة الدواء عند الباب',
      'podStep1':      'إثبات التسليم خطوة 1 من 2 · الطلب #{id}',
      'myEarningsTab': '💰 أرباحي',
      'companyCashTab': '🏦 نقد الشركة',
      'myCommissionToday': 'عمولتي اليوم',
      'deliveriesCountTemplate': '↑ {n} توصيلات',
      'commissionRateLine1': 'نسبة عمولتك (يحددها المسؤول):\n',
      'commissionRatePercent': '10% من إجمالي كل طلب',
      'weekLabel':     'الأسبوع',
      'monthLabel':    'الشهر',
      'hourlyCap':     'بالساعة',
      'deliveriesStatLabel': 'التوصيلات',
      'failedStatLabel': 'فاشلة',
      'distanceStatLabel': 'المسافة',
      'ratingStatLabel': 'التقييم',
      'workAndHours':  'العمل والساعات',
      'shiftTimeToday': 'مدة الدوام اليوم',
      'liveStatus':    '● مباشر',
      'pausedStatus':  '◯ متوقف',
      'idleStatLabel': 'خمول',
      'kdPerHourLabel': 'د.ك / ساعة',
      'shiftStarted':  'بدأ الدوام',
      'cashToHandOver': 'النقد المطلوب تسليمه',
      'cashHandoverExplainer': '💡 هذا هو النقد الذي حصّلته من الطلبات المدفوعة نقداً.\nسلّمه لمديرك — يقوم بمسح رمز QR — ويتم تصفيته.',
      'cashHandoverQrToast': '📷 رمز تسليم النقد — أظهره للمدير للتأكيد',
      'showQrToManager': '📷 أظهر الرمز للمدير وسلّم النقد',
      'bankWithdrawToast': '🏦 سحب بنكي — أرفق الإيصال للمتابعة',
      'withdrawToBank': '🏦 سحب إلى البنك — أرفق الإيصال',
      'allClearNoCash': '✓ لا يوجد نقد للتسليم',
      'recentHandovers': 'التسليمات الأخيرة',
      'noHandoversYet': 'لا توجد تسليمات حتى الآن. بعد تسليم النقد، سيظهر السجل هنا.',
      'totalHandedOver': 'إجمالي ما تم تسليمه',
      'bankBadge':     'بنك',
      'pendingBadge':  '⏳ قيد الانتظار',
      'confirmedBadge': '✓ مؤكد',
    },
  };

  String get(String key) => _dict[locale]?[key] ?? _dict['en']?[key] ?? key;
}

/// context.tr('key') — shorthand used across every screen to look up a
/// translated string for the driver's current language.
/// Deliberately uses `read`, not `watch`: `watch` can ONLY be called
/// during a widget's build() method and throws if called from a callback
/// (onTap, onPressed, initState, async methods like save/submit handlers)
/// — and this helper needs to work in all of those places, not just build.
/// In practice this still updates correctly on language change because
/// every screen that displays translated text also watches AppViewModel
/// directly for other things (driver info, shift status, etc.), which
/// triggers the rebuild that re-reads these strings.
extension AppStringsContext on BuildContext {
  String tr(String key) => AppStrings(read<AppViewModel>().language).get(key);
}
