/// Lightweight i18n matching the HTML prototype's I18N dictionary.
class AppStrings {
  const AppStrings(this.locale);
  final String locale;

  static const Map<String, Map<String, String>> _dict = {
    'en': {
      'appName':       'WASFA Rider',
      'onShift':       'ON SHIFT',
      'offShift':      'OFF SHIFT',
      'today':         'TODAY',
      'welcome':       'Welcome',
      'enterPhone':    'Enter your phone number',
      'sendCode':      'Send code',
      'enterCode':     'Enter verification code',
      'sentTo':        'We sent a 6-digit code to',
      'resend':        'Resend code',
      'verify':        'Verify',
      'setupVehicle':  'Set up your vehicle',
      'vehicleType':   'Vehicle type',
      'plate':         'Plate number',
      'continue_':     'Continue',
      'motorbike':     'Motorbike',
      'scooter':       'Scooter',
      'car':           'Car',
      'pickLang':      'Choose your language',
      'english':       'English',
      'arabic':        'العربية',
      'logout':        'Logout',
      'orders':        'Orders',
      'home':          'Home',
      'profile':       'Profile',
      'history':       'History',
      'earnings':      'Earnings',
      'active':        'Active',
      'done':          'Done',
      'all':           'All',
      'swipeArrived':  'Swipe when arrived',
      'headingToPharmacy': "I'm on my way to pharmacy",
      'confirmPickedUp': 'Confirm items picked up',
      'headingToPatient': 'Heading to patient (open directions)',
      'arrivedAtPatient': "I've arrived at patient",
      'cantDeliver':   "Can't deliver — failed",
      'openInMaps':    'OPEN IN MAPS',
      'call':          'Call',
      'maps':          'Maps',
      'waze':          'Waze',
    },
    'ar': {
      'appName':       'سائق وصفة',
      'onShift':       'في الخدمة',
      'offShift':      'خارج الخدمة',
      'today':         'اليوم',
      'welcome':       'أهلاً بك',
      'enterPhone':    'أدخل رقم هاتفك',
      'sendCode':      'إرسال الرمز',
      'enterCode':     'أدخل رمز التحقق',
      'sentTo':        'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'resend':        'إعادة الإرسال',
      'verify':        'تحقق',
      'setupVehicle':  'إعداد المركبة',
      'vehicleType':   'نوع المركبة',
      'plate':         'رقم اللوحة',
      'continue_':     'متابعة',
      'motorbike':     'دراجة نارية',
      'scooter':       'سكوتر',
      'car':           'سيارة',
      'pickLang':      'اختر لغتك',
      'english':       'English',
      'arabic':        'العربية',
      'logout':        'تسجيل الخروج',
      'orders':        'الطلبات',
      'home':          'الرئيسية',
      'profile':       'الملف الشخصي',
      'history':       'السجل',
      'earnings':      'الأرباح',
      'active':        'نشط',
      'done':          'مكتمل',
      'all':           'الكل',
      'swipeArrived':  'اسحب عند الوصول',
      'headingToPharmacy': 'في طريقي إلى الصيدلية',
      'confirmPickedUp': 'تأكيد استلام الأصناف',
      'headingToPatient': 'في طريقي إلى المريض',
      'arrivedAtPatient': 'وصلت إلى المريض',
      'cantDeliver':   'تعذر التسليم',
      'openInMaps':    'فتح في الخريطة',
      'call':          'اتصال',
      'maps':          'خرائط',
      'waze':          'ويز',
    },
  };

  String get(String key) => _dict[locale]?[key] ?? _dict['en']?[key] ?? key;
}
